# Generated by Django 4.1 on 2022-11-23 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("violations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredcomplaints",
            name="case_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("In-Progress", "In-Progress"),
                    ("Closed", "Closed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registeredcomplaints",
            name="complaint_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registeredcomplaints",
            name="negative_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registeredcomplaints",
            name="registered_against",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_object_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registeredcomplaints",
            name="registered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="violationlogs",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="violationlogs",
            name="violation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="violations.violations",
            ),
        ),
        migrations.AddField(
            model_name="violations",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="violations",
            name="name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
