# Generated by Django 4.1 on 2023-01-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0003_violationlogs_registered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="violationlogs",
            name="violation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
