# Generated by Django 4.1 on 2023-01-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0004_violationlogs_violation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="violationlogs",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
