# Generated by Django 4.1 on 2023-01-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0005_violationlogs_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredcomplaints",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
