# Generated by Django 4.1 on 2023-01-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0006_registeredcomplaints_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="violations",
            name="neg_score",
            field=models.IntegerField(default=0),
        ),
    ]
