# Generated by Django 4.1 on 2023-02-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("violations", "0007_violations_neg_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="violations",
            name="tag",
            field=models.IntegerField(default=0),
        ),
    ]
