# Generated by Django 4.1 on 2023-01-30 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_checkout_delete_employeeofthemonth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=50, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="paidleaves",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="paidleaves",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
