# Generated by Django 4.1 on 2023-01-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_announcements_attendance_check_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="is_present",
            field=models.BooleanField(default=True),
        ),
    ]
