# Generated by Django 4.1 on 2022-11-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_metrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeOfTheMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
