# Generated by Django 4.1 on 2023-02-02 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emp_metrics", "0003_employeeofthemonth_date_employeeofthemonth_emp_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancemetrics",
            name="complaint_freq",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="performancemetrics",
            name="dependability",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="performancemetrics",
            name="employee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="performancemetrics",
            name="employee_of_month_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="performancemetrics",
            name="overall_performance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="performancemetrics",
            name="productivity_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="performancemetrics",
            name="punctuality_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="performancemetrics",
            name="violations_freq",
            field=models.IntegerField(default=0),
        ),
    ]
